In [1]:
import pandas as pd

In [2]:
citibikes_data = ["resources/202208.csv", "resources/202209.csv", "resources/202210.csv", "resources/202211.csv", "resources/202212.csv"]

In [3]:
# Create an empty list to store each dataframe
citibikes_list = []

# Loop through each file in the list
for data in citibikes_data:
    # Read the file into a dataframe
    citibikes = pd.read_csv(data)

    # Append the dataframe to the list
    citibikes_list.append(citibikes)

# Concatenate all dataframes in the list into one dataframe
citibikes_df = pd.concat(citibikes_list)

# Show dataframe
citibikes_df

C:\Users\tonyn\AppData\Local\Temp\ipykernel_26548\3532138886.py:7: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  citibikes = pd.read_csv(data)
C:\Users\tonyn\AppData\Local\Temp\ipykernel_26548\3532138886.py:7: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  citibikes = pd.read_csv(data)
C:\Users\tonyn\AppData\Local\Temp\ipykernel_26548\3532138886.py:7: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  citibikes = pd.read_csv(data)
C:\Users\tonyn\AppData\Local\Temp\ipykernel_26548\3532138886.py:7: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  citibikes = pd.read_csv(data)
C:\Users\tonyn\AppData\Local\Temp\ipykernel_26548\3532138886.py:7: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  citibikes = pd.read_csv(data)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,428051654CF1145B,classic_bike,2022-08-28 00:34:58,2022-08-28 00:55:20,Walker St & Baxter St,5351.07,Lexington Ave & E 24 St,6089.07,40.717411,-73.999573,40.740259,-73.984092,member
1,7282036E3ECDDD65,classic_bike,2022-08-31 16:33:38,2022-08-31 16:35:17,Lexington Ave & E 29 St,6164.09,Lexington Ave & E 24 St,6089.07,40.743116,-73.982154,40.740259,-73.984092,member
2,375C59BE1271E31C,electric_bike,2022-08-27 23:22:10,2022-08-27 23:34:57,E 132 St & Madison Ave,7748.02,Melrose Ave & E 150 St,7879.01,40.810224,-73.937195,40.816827,-73.917338,member
3,7281A7F21CE571AF,classic_bike,2022-08-26 19:01:01,2022-08-26 19:09:26,Lexington Ave & E 29 St,6164.09,E 13 St & 2 Ave,5820.08,40.743116,-73.982154,40.731539,-73.985302,member
4,A5093D7D77713F87,classic_bike,2022-08-25 22:16:16,2022-08-25 22:29:13,E 16 St & Irving Pl,5938.11,W 31 St & 7 Ave,6331.01,40.735367,-73.987974,40.749156,-73.991600,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

In [4]:
citibikes_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [5]:
citibikes_df.isnull().values.any()

True

In [6]:
citibikes_df.dropna(inplace = True)
citibikes_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,428051654CF1145B,classic_bike,2022-08-28 00:34:58,2022-08-28 00:55:20,Walker St & Baxter St,5351.07,Lexington Ave & E 24 St,6089.07,40.717411,-73.999573,40.740259,-73.984092,member
1,7282036E3ECDDD65,classic_bike,2022-08-31 16:33:38,2022-08-31 16:35:17,Lexington Ave & E 29 St,6164.09,Lexington Ave & E 24 St,6089.07,40.743116,-73.982154,40.740259,-73.984092,member
2,375C59BE1271E31C,electric_bike,2022-08-27 23:22:10,2022-08-27 23:34:57,E 132 St & Madison Ave,7748.02,Melrose Ave & E 150 St,7879.01,40.810224,-73.937195,40.816827,-73.917338,member
3,7281A7F21CE571AF,classic_bike,2022-08-26 19:01:01,2022-08-26 19:09:26,Lexington Ave & E 29 St,6164.09,E 13 St & 2 Ave,5820.08,40.743116,-73.982154,40.731539,-73.985302,member
4,A5093D7D77713F87,classic_bike,2022-08-25 22:16:16,2022-08-25 22:29:13,E 16 St & Irving Pl,5938.11,W 31 St & 7 Ave,6331.01,40.735367,-73.987974,40.749156,-73.991600,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649647,CB2EE50F60A58C7B,classic_bike,2022-12-12 08:38:46,2022-12-12 08:46:12,E 41 St & Madison Ave (SW corner),6474.12,6 Ave & W 33 St,6364.07,40.752165,-73.979922,40.749013,-73.988484,member
1649648,3C0DF3280FEB1350,classic_bike,2022-12-12 13:06:32,2022-12-12 13:19:58,Peck Slip & South St,5096.12,Vesey St & Church St,5216.06,40.707689,-74.001254,40.712220,-74.010472,member
1649649,B916E63B630D5020,classic_bike,2022-12-18 01:15:22,2022-12-18 01:48:15,E 41 St & Madison Ave (SW corner),6474.12,Lenox Ave & W 111 St,7602.05,40.752399,-73.980150,40.798786,-73.952300,member
1649650,21EAC007BE7D4161,classic_bike,2022-12-08 23:09:54,2022-12-08 23:26:37,W 37 St & 10 Ave,6611.02,W 70 St & Amsterdam Ave,7207.08,40.756604,-73.997901,40.777480,-73.982886,member
1649651,538408C4A16F4415,electric_bike,2022-12-21 07:26:14,2022-12-21 07:31:40,W 37 St & 10 Ave,6611.02,6 Ave & W 33 St,6364.07,40.756604,-73.997901,40.749013,-73.988484,member

In [7]:
citibikes_df.to_csv("resources/citibikes_combine_2.csv", index=False)